### ISSUE TITLE
老哥为啥把后端单体项目删了

### ISSUE THREAD

**Issue by ClearTrifles** [0oHo0/DuuOJ#1]
哥，后端单体为啥删除了？我还想学习学习呢。有精力能重传下吗？

**Comment by 0oHo0** [comment]
因为单体项目功能很多没做完整，和Readme中的描述出入太大，所以删除了。

**Comment by 0oHo0** [comment]
> 哥，后端单体为啥删除了？我还想学习学习呢。有精力能重传下吗？

因为单体项目功能很多没做完整，和Readme中的描述出入太大，所以删除了。
